# Results list page, this is the actual page that we are targeting.
bexar_list_url = "https://bexar.acttax.com/act_webdev/bexar/showlist.jsp"

[headers]

# Pretend to be Chrome on Windows to blend in as much as possible.
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
content-type = "application/x-www-form-urlencoded"
accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
referer = "https://bexar.acttax.com/act_webdev/bexar/index.jsp"

